ursjoss/scipamato

CHANGELOG.asciidoc, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel.java, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/paper/entry/EditablePaperPanel.java, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/paper/search/PaperSearchCriteriaPage.java, implementation/scipamato/scipamato-core-web/src/test/java/ch/difty/scipamato/core/web/paper/common/SearchablePaperPanelTest.java, implementation/scipamato/scipamato-core-web/src/test/java/ch/difty/scipamato/core/web/paper/search/PaperSearchCriteriaPageTest.java
=> Don't close the Search Condition Edit Page after updating one field.

implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel$TabPanel4.html
=> [#63] - Core: Layout of New fields tab in Paper Edit Page

CHANGELOG.asciidoc, implementation/scipamato/scipamato-public-web/pom.xml, implementation/scipamato/scipamato-public-web/src/main/java/ch/difty/scipamato/publ/web/themes/markup/html/publ/ScipamatoPublicLessReference.java, implementation/scipamato/scipamato-public-web/src/main/java/ch/difty/scipamato/publ/web/themes/markup/html/publ/ScipamatoPublicTheme.java, implementation/scipamato/scipamato-public-web/src/main/resources/application.properties
=> Bug/73 Fix feature less-used-over-css (starting SciPaMaTo-Public with profile development)

CHANGELOG.asciidoc, implementation/scipamato/pom.xml, implementation/scipamato/scipamato-common-wicket/pom.xml, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/newsletter/edit/NewsletterEditPage.java, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/newsletter/list/NewsletterListPage.java, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel.java, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/paper/entry/EditablePaperPanel.java, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/paper/entry/PaperEntryPage.java, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/paper/list/PaperListPage.java, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/paper/result/ResultPanel.java, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/paper/search/PaperSearchPage.java, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/paper/search/SearchOrderPanel.java, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/user/UserListPage.java, implementation/scipamato/scipamato-core-web/src/test/java/ch/difty/scipamato/core/web/newsletter/list/NewsletterListPageTest.java, implementation/scipamato/scipamato-core-web/src/test/java/ch/difty/scipamato/core/web/paper/result/ResultPanelInEditModeTest.java, implementation/scipamato/scipamato-core-web/src/test/java/ch/difty/scipamato/core/web/paper/result/ResultPanelInSearchModeTest.java, implementation/scipamato/scipamato-core-web/src/test/java/ch/difty/scipamato/core/web/paper/search/PaperSearchPageTest.java
Upgrade from font-awesome 4.7.0 to 5.7.1
=> Font awesome

CHANGELOG.asciidoc, implementation/scipamato/scipamato-core-entity/src/main/java/ch/difty/scipamato/core/entity/search/IntegerSearchTerm.java, implementation/scipamato/scipamato-core-entity/src/test/java/ch/difty/scipamato/core/entity/search/IntegerSearchTermTest.java, implementation/scipamato/scipamato-core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/paper/searchorder/IntegerSearchTermEvaluator.java, implementation/scipamato/scipamato-core-persistence-jooq/src/test/java/ch/difty/scipamato/core/persistence/paper/searchorder/IntegerSearchTermEvaluatorTest.java
=> Bug/84: Searching for publication year ranges broken

CHANGELOG.asciidoc, implementation/scipamato/build.gradle.kts, implementation/scipamato/core/persistence-jooq/src/intTest/java/ch/difty/scipamato/core/persistence/paper/searchorder/StringSearchTermEvaluatorTest.java, implementation/scipamato/core/persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/ConditionalSupplier.java, implementation/scipamato/core/persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/paper/searchorder/StringSearchTermEvaluator.java
WIP and TBD
Eventually fixes #91
=> WIP Feature/91 complex search enhance method search

implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/paper/entry/EditablePaperPanel.java
=> Use ObjIntConsumer<Paper> over BiConsumer<Paper, Integer>

CHANGELOG.asciidoc, implementation/scipamato/common/persistence-api/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, implementation/scipamato/common/persistence-jooq/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, implementation/scipamato/common/utils/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, implementation/scipamato/core/persistence-jooq/src/test/java/ch/difty/scipamato/core/persistence/code/JooqCodeRepoTest.java, implementation/scipamato/core/persistence-jooq/src/test/java/ch/difty/scipamato/core/persistence/codeclass/JooqCodeClassRepoTest.java, implementation/scipamato/core/persistence-jooq/src/test/java/ch/difty/scipamato/core/persistence/keyword/JooqKeywordRepoTest.java, implementation/scipamato/core/persistence-jooq/src/test/java/ch/difty/scipamato/core/persistence/newsletter/JooqNewsletterServiceTest.java, implementation/scipamato/core/persistence-jooq/src/test/java/ch/difty/scipamato/core/persistence/paper/JooqPaperServiceTest.java, implementation/scipamato/core/persistence-jooq/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, implementation/scipamato/gradle/wrapper/gradle-wrapper.properties, implementation/scipamato/public/persistence-jooq/src/test/java/ch/difty/scipamato/publ/persistence/newstudies/JooqNewStudyTopicServiceTest.java, implementation/scipamato/public/persistence-jooq/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
=> Bug/101: Enabling the upgrade to gradle-5.5.1 by removing the need to inline mock with mockito

CHANGELOG.asciidoc, implementation/scipamato/build.gradle.kts, implementation/scipamato/buildSrc/src/main/kotlin/Lib.kt, implementation/scipamato/common/test/build.gradle.kts, implementation/scipamato/core/persistence-jooq/src/test/java/ch/difty/scipamato/core/persistence/code/JooqCodeRepoTest.java, implementation/scipamato/core/persistence-jooq/src/test/java/ch/difty/scipamato/core/persistence/codeclass/JooqCodeClassRepoTest.java, implementation/scipamato/core/persistence-jooq/src/test/java/ch/difty/scipamato/core/persistence/keyword/JooqKeywordRepoTest.java, implementation/scipamato/core/persistence-jooq/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
=> Bump mockito to 3.0.2, re-enable inline mocking for core-persistence-jooq and reactivate tests

CHANGELOG.asciidoc, implementation/scipamato/core/persistence-jooq/src/intTest/java/ch/difty/scipamato/core/persistence/paper/searchorder/StringSearchTermEvaluatorIntegrationTest.java, implementation/scipamato/core/persistence-jooq/src/intTest/java/ch/difty/scipamato/core/persistence/paper/searchorder/StringSearchTermEvaluatorTest.java, implementation/scipamato/core/persistence-jooq/src/intTest/java/ch/difty/scipamato/core/persistence/paper/slim/JooqPaperSlimBySearchOrderRepoIntegrationTest.java, implementation/scipamato/core/persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/paper/searchorder/StringSearchTermEvaluator.java, implementation/scipamato/core/persistence-jooq/src/test/java/ch/difty/scipamato/core/persistence/paper/slim/JooqPaperSlimBySearchOrderRepoTest.java
=> [109] - Fix searching in methods fields with positive and negative search term

implementation/scipamato/build.gradle.kts, implementation/scipamato/buildSrc/src/main/kotlin/Lib.kt, implementation/scipamato/common/entity/detekt-baseline.xml, implementation/scipamato/common/persistence-jooq-test/detekt-baseline.xml, implementation/scipamato/common/test/detekt-baseline.xml, implementation/scipamato/common/utils/detekt-baseline.xml, implementation/scipamato/core/logic/detekt-baseline.xml, implementation/scipamato/core/web/detekt-baseline.xml
Hi, 
Here is setup for Detek, Spek, Kluent, Kwik and MockK (Resolves #124).
Some notes:
* I left the Detekt config file empty which means: default config
* I created baselines for Detekt. So there is by definition 0 issue at the moment.
* Detekt issues are properly reported to sonar: https://sonarcloud.io/project/issues?id=jcornaz_scipamato&open=AW2njdsGDfDDVHn5uy4s&resolved=false&types=CODE_SMELL
* I added [MockK](https://mockk.io) despite the fact that it wasn't mentioned in #124, tell me if you want me to remove it.
* I added the `jcenter` repository (required by Kluent and Kwik)
=> Setup Detekt, Spek, Kluent, Kwik and MockK

CHANGELOG.asciidoc, implementation/scipamato/build.gradle.kts, implementation/scipamato/buildSrc/src/main/kotlin/Lib.kt, implementation/scipamato/common/persistence-jooq/build.gradle.kts, implementation/scipamato/common/utils/src/test/kotlin/ch/difty/scipamato/common/entity/newsletter/PublicationStatusTest.kt, implementation/scipamato/common/utils/src/test/kotlin/ch/difty/scipamato/common/persistence/paging/SortTest.kt, implementation/scipamato/core/entity/src/test/kotlin/ch/difty/scipamato/core/entity/PaperTest.kt, implementation/scipamato/core/entity/src/test/kotlin/ch/difty/scipamato/core/entity/UserTest.kt, implementation/scipamato/core/persistence-jooq/src/intTest/kotlin/ch/difty/scipamato/core/persistence/JooqKeywordRepoIntegrationTest.kt, implementation/scipamato/core/persistence-jooq/src/intTest/kotlin/ch/difty/scipamato/core/persistence/JooqPaperRepoIntegrationTest.kt, implementation/scipamato/core/persistence-jooq/src/intTest/kotlin/ch/difty/scipamato/core/persistence/paper/searchorder/AuditSearchTermEvaluatorTest.kt, implementation/scipamato/core/persistence-jooq/src/intTest/kotlin/ch/difty/scipamato/core/persistence/paper/searchorder/StringSearchTermEvaluatorIntegrationTest.kt, implementation/scipamato/core/persistence-jooq/src/intTest/kotlin/ch/difty/scipamato/core/persistence/paper/searchorder/StringSearchTermEvaluatorTest.kt, implementation/scipamato/core/persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/code/JooqCodeServiceTest.kt, implementation/scipamato/core/persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/codeclass/JooqCodeClassServiceTest.kt, implementation/scipamato/core/persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/keyword/JooqKeywordServiceTest.kt, implementation/scipamato/core/persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/newsletter/JooqNewsletterTopicServiceTest.kt, implementation/scipamato/core/persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/paper/slim/JooqPaperSlimBySearchOrderRepoTest.kt, implementation/scipamato/core/persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/search/SearchOrderFilterConditionMapperTest.kt, implementation/scipamato/core/web/build.gradle.kts, implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/web/paper/PaperAttachmentProviderTest.java, implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/web/paper/SearchConditionProviderTest.java, implementation/scipamato/public/web/build.gradle.kts, implementation/scipamato/public/web/src/test/java/ch/difty/scipamato/publ/web/paper/browse/PublicPaperProviderTest.java
=> Chore/136 Upgrade to Spring-Boot 2.2.0 (and with it Flyway 6 and jOOQ 3.12.1)

implementation/scipamato/build.gradle.kts, implementation/scipamato/buildSrc/src/main/kotlin/Lib.kt
=> User reckon for managing the version

.github/workflows/check.yml, .github/workflows/sonar.yml
Resolves #135 .
Thanks to @jcornaz
=> Cache the gradle cache folder with github Action build jobs.

.github/workflows/check.yml, .github/workflows/sonar.yml
=> Discard gradle cache with updates of the gradle wrapper version

core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/code/JooqCodeRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/codeclass/JooqCodeClassRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/keyword/JooqKeywordRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/newsletter/JooqNewsletterTopicRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/user/UserUpdateSetStepSetter.java, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/AuditFieldsTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/codeclass/JooqCodeClassRepoTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/newsletter/JooqNewsletterServiceTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/newsletter/JooqNewsletterTopicRepoTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/newsletter/JooqNewsletterTopicServiceTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/paper/slim/JooqPaperSlimRepoTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/paper/slim/JooqPaperSlimServiceTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/search/JooqSearchOrderRepoTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/search/JooqSearchOrderServiceTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/search/SearchOrderRecordMapperTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/search/SearchOrderUpdateSetStepSetterTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/user/JooqUserServiceTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/user/UserUpdateSetStepSetterTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/user/UserUpdateSetStepSetterWithoutPasswordTest.kt
Replace some `trueCondition`s with `noCondition`.
See https://blog.jooq.org/2020/03/06/create-empty-optional-sql-clauses-with-jooq/
=> jOOQ noCondition

CHANGELOG.asciidoc, buildSrc/src/main/kotlin/Lib.kt
- wicket-bootstrap from 2.0.12 to 2.0.13
- font-awesome from 5.11.2 to 5.12.0
- kwik from 0.5.0 to 0.6.0
=> Dependency updates

CHANGELOG.adoc, core/core-pubmed-api/src/integration-test/kotlin/ch/difty/scipamato/core/pubmed/ScipamatoPubmedArticleIntegrationTest.kt, core/core-pubmed-api/src/main/java/ch/difty/scipamato/core/pubmed/Extensions.kt, core/core-pubmed-api/src/main/java/ch/difty/scipamato/core/pubmed/PubmedArticleResult.kt, core/core-pubmed-api/src/main/java/ch/difty/scipamato/core/pubmed/ScipamatoPubmedArticle.java, core/core-pubmed-api/src/test/kotlin/ch/difty/scipamato/core/pubmed/ScipamatoPubmedArticleTest.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel.utf8.properties, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel_de.utf8.properties, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/entry/EditablePaperPanel.java, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/entry/Extensions.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/entry/EditablePaperPanelInEditModeTest.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/entry/EditablePaperPanelTest.kt
=> [202] - Auto-correct ahead-of-print articles from PubMed

public/public-web/src/main/java/ch/difty/scipamato/publ/web/paper/browse/PublicPage.html
=> Improve Layout of various pages for small screens

CHANGELOG.adoc, common/common-wicket/src/main/java/ch/difty/scipamato/common/web/pages/login/AbstractLoginPage.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/code/CodeEditHeaderPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/code/CodeEditTranslationPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/code/CodeListFilterPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/codeclass/CodeClassEditHeaderPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/codeclass/CodeClassEditTranslationPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/codeclass/CodeClassListFilterPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/keyword/KeywordEditHeaderPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/keyword/KeywordEditTranslationPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/keyword/KeywordListFilterPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/newsletter/edit/NewsletterEditPage.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/newsletter/list/NewsletterListPage.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/newsletter/topic/NewsletterTopicEditHeaderPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/newsletter/topic/NewsletterTopicEditTranslationPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/newsletter/topic/NewsletterTopicListFilterPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel$TabPanel1.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel$TabPanel2.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel$TabPanel3.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel$TabPanel4.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel$TabPanel6.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel$TabPanel7.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/list/PaperListPage.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/user/UserListPage.html, public/public-web/src/main/java/ch/difty/scipamato/publ/web/paper/browse/PublicPage.html, public/public-web/src/main/java/ch/difty/scipamato/publ/web/paper/browse/SimpleFilterPanel.html
=> Improve Layout of various pages for small/medium screens

CHANGELOG.adoc, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/entry/PaperEntryPage.java
=> [236] Prepopulate field 'result exposure rate' with value 'µg/m3' for new papers

core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/entry/EditablePaperPanel.java
=> Only allow uploading attachments once paper is saved

CHANGELOG.adoc, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/entry/EditablePaperPanel.java
=> [247] Fix captions of paper summary pdf

CHANGELOG.adoc, core/core-entity/src/main/java/ch/difty/scipamato/core/AttachmentAware.java, core/core-entity/src/main/java/ch/difty/scipamato/core/entity/Paper.java, core/core-entity/src/main/java/ch/difty/scipamato/core/entity/search/SearchCondition.java, core/core-entity/src/test/kotlin/ch/difty/scipamato/core/entity/PaperTest.kt, core/core-entity/src/test/kotlin/ch/difty/scipamato/core/entity/search/SearchConditionTest.kt, core/core-persistence-jooq/src/integration-test/kotlin/ch/difty/scipamato/core/persistence/paper/slim/JooqPaperSlimBySearchOrderRepoIntegrationTest.kt, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/paper/searchorder/JooqBySearchOrderRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/search/JooqSearchOrderRepo.java, core/core-persistence-jooq/src/main/resources/db/migration/V21032900300000__search_attachment.sql, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/search/JooqSearchOrderRepoTest.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel$TabPanel6.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel.utf8.properties, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel_de.utf8.properties, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/common/PaperPanelTest.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/common/SearchablePaperPanelTest.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/entry/EditablePaperPanelInEditModeTest.kt
=> feat(core): [#265]: Complex search for papers with or without attachments or with attachment name

CHANGELOG.adoc, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/paper/searchorder/JooqBySearchOrderRepo.java, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/paper/slim/JooqPaperSlimBySearchOrderRepoTest.kt
=> fix: [#294] Apply regular search patterns to newsletter issue, headline and attachment name

CHANGELOG.adoc, core/core-entity/src/main/java/ch/difty/scipamato/core/entity/CodeBoxAware.java, core/core-entity/src/main/java/ch/difty/scipamato/core/entity/Paper.java, core/core-entity/src/main/java/ch/difty/scipamato/core/entity/search/SearchCondition.java, core/core-entity/src/test/kotlin/ch/difty/scipamato/core/entity/search/SearchConditionTest.kt, core/core-persistence-jooq/src/integration-test/kotlin/ch/difty/scipamato/core/persistence/search/JooqSearchOrderRepoIntegrationTest.kt, core/core-persistence-jooq/src/integration-test/resources/db/migration/V21111420200000__search_excluding_code.sql, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/paper/searchorder/JooqBySearchOrderRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/search/JooqSearchOrderRepo.java, core/core-persistence-jooq/src/main/resources/db/migration/V21111416320000__search_condition_code_excluded.sql, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/paper/slim/JooqPaperSlimBySearchOrderRepoTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/search/JooqSearchOrderRepoTest.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel$TabPanel3.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel.utf8.properties, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel_de.utf8.properties, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/common/SearchablePaperPanelTest.kt
=> feat: [#292] Allow searches with explicit code exclusions

CHANGELOG.adoc, build.gradle.kts, buildSrc/src/main/kotlin/Lib.kt, common/common-entity/build.gradle.kts, core/core-entity/build.gradle.kts, core/core-pubmed-api/build.gradle.kts, core/core-web/build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, public/public-web/build.gradle.kts
=> chore(deps): Dependencies

build.gradle.kts, buildSrc/src/main/kotlin/Lib.kt
=> feat: [#352] Remove dependency on jcenter

build.gradle.kts
fix regression introduced in #446. Since then, only integrationTests were executed.
=> fix: restore running unit tests

core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/jasper/referenceabstract/PaperReferenceAbstract.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/jasper/referenceabstract/PaperReferenceAbstractDataSource.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/result/ResultPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/result/ResultPanel.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/result/ResultPanel.utf8.properties, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/result/ResultPanel_de.utf8.properties, core/core-web/src/main/java/ch/difty/scipamato/core/web/resources/jasper/PaperReferenceAbstractResourceReference.java, core/core-web/src/main/resources/ch/difty/scipamato/core/web/resources/jasper/paper_reference_abstract_A4.jrxml, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/jasper/ExportEntityTest.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/jasper/referenceabstract/PaperReferenceAbstractDataSourceTest.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/jasper/referenceabstract/PaperReferenceAbstractTest.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/result/ResultPanelTest.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/resources/jasper/PaperReferenceAbstractResourceReferenceTest.kt
=> feat: [#604] Reference Abstract Report

core/core-web/src/main/java/ch/difty/scipamato/core/ScipamatoCoreApplication.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/AbstractWicketTest.kt
Resolves #620
After migration, we'll probably simply revert the merge commit.
=> chore: Update abstract from pubmed where missing

core/core-entity/src/main/java/ch/difty/scipamato/core/entity/Paper.java, core/core-entity/src/main/java/ch/difty/scipamato/core/entity/search/SearchTerm.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/AbstractRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/JooqEntityRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/JooqReadOnlyRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/ReadOnlyRepository.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/code/JooqCodeRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/codeclass/JooqCodeClassRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/keyword/JooqKeywordRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/newsletter/JooqNewsletterRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/paper/JooqPaperRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/paper/slim/JooqPaperSlimRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/search/JooqSearchOrderRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/user/JooqUserRepo.java, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/search/JooqSearchOrderRepoTest.kt
- nullability
- final
- resolve some deprecation warnings
- minor other stuff
=> refactor: Massage core repos

core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/FactoryFunctions.kt, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/jobs/code/CodeSyncConfig.kt, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/jobs/codeclass/CodeClassSyncConfig.kt, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/jobs/keyword/KeywordSyncConfig.kt, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/jobs/language/LanguageSyncConfig.kt, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/jobs/newsletter/NewStudySyncConfig.kt, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/jobs/newsletter/NewStudyTopicSyncConfig.kt, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/jobs/newsletter/NewsletterSyncConfig.kt, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/jobs/newsletter/NewsletterTopicSyncConfig.kt, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/jobs/newstudypagelink/NewStudyPageLinkSyncConfig.kt, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/jobs/paper/PaperSyncConfig.kt
Create factoryFunctions as calling constructor on TypeAlias seems to  not work anymore
=> refactor: pre-kotlin-2 migration

CHANGELOG.adoc, build.gradle.kts, gradle/libs.versions.toml
=> chore: [#718] Switch to jk1/Gradle-License-Report
