CHANGELOG.asciidoc, implementation/scipamato/scipamato-core-web/src/main/java/ch/difty/scipamato/core/web/paper/result/ResultPanel.java
* Issuing a submit from the paper entry page (e.g. by using prev/next
button, creating a pdf or retrieving data from pubmed) and
subsequently using the applications or the browsers back button to
return to the calling page (PaperListPage or PaperSearchCriteriaPage)
resulted in a NPE when clicking one of the PDF buttons in the Result
Panel.
* Apparently, deserializing the PaperPanel rendered the reportSources
report null. This isn't handled gracefully by JRFiller and results
in the NPE.
* The work around for this is recreate the ResourceLinks for the PDFs
after calling defaultReadObject within readObject of the Panel.
=> [2] - Core: Using Back button from PaperEntryPage breaks PDF Report generation

CHANGELOG.asciidoc, implementation/scipamato/scipamato-core-sync/src/main/resources/application.properties, implementation/scipamato/scipamato-core-sync/src/test/resources/application.properties
Hikari was already used in `scipamato-core-sync`.
The config was ok, but could be improved to omit some warnings:
- raise `max-lifetime` to 30000 to avoid warning
- remove `idle-timeout`, which is not active in a fixed sized pool anyhow.
=> scipamato-core-sync: raise max-lifetime and remove idle-timout in hikari configuration

CHANGELOG.asciidoc, implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/model/SearchOrderModel.java, implementation/scipamato/core/web/src/main/java/ch/difty/scipamato/core/web/paper/search/SearchOrderSelectorPanel.java, implementation/scipamato/core/web/src/test/java/ch/difty/scipamato/core/web/model/SearchOrderModelTest.java
Sorts the search orders by id descendingly and limits the search results to the top 200 instead of top 20.
Fixes #105.
=> [105] - Sort search orders by id desc and show top 200 instead of 20

.github/workflows/check.yml, .github/workflows/sonar.yml
Hi, 
Here are small improvement for your the github workflow you may want.
The idea is to:
* Run the workflows only for the branch `master` (and pull requests against that branch)
* Run the workflows for all new pushed tags. (will run for the tagged commit, even if you push more commits alltogether)
* Run only the check tasks for changes made in `implementation/scipamato`
You can see there results here:
* workflow status and log: https://github.com/jcornaz/scipamato/actions
* sonar report: https://sonarcloud.io/dashboard?id=jcornaz_scipamato
=> Chore/improve GitHub workflows

core/core-persistence-jooq/build.gradle.kts, core/core-persistence-jooq/src/integration-test/resources/application.properties, public/public-persistence-jooq/build.gradle.kts, public/public-persistence-jooq/src/integration-test/resources/application.properties
- remove redundancy between generated `jooqConfig.xml` file and gradle jooqModelator config
- remove obsolete warnings about keeping related configuration in sync
=> Clean up build.gradle.kts of persistance-jooq projects

CHANGELOG.adoc, public/public-web/src/main/kotlin/ch/difty/scipamato/publ/web/paper/browse/PublicPage.kt, public/public-web/src/main/kotlin/ch/difty/scipamato/publ/web/paper/browse/PublicPaperDetailPage.kt, public/public-web/src/test/kotlin/ch/difty/scipamato/publ/web/paper/browse/PublicPageTest.kt
=> [238] SciPaMaTo-Public: Hide Back-Button from paper detail page when opened from result panel

.github/workflows/check.yml, .github/workflows/sonar.yml
Resolves #260.
Requires an Access Token on Docker hub. Store it and the login name as github secrets `DOCKERHUB_TOKEN` and `DOCKERHUB_USERNAME`
=> fix: [#260] Log in to dockerhub in github actions

buildSrc/src/main/kotlin/Lib.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/search/SearchOrderSelectorPanelInEditModeTest.kt
Resolves #262.
ConfirmationBehavior was broken when used with bootstrap 3.4.1
(see https://github.com/l0rdn1kk0n/wicket-bootstrap/pull/895)
Bumping wicket-bootstrap to 4.0.3 will bring in the fixed version.
The additional tests cover more scenario, but unfortunately don't capture
the broken scenario (no red test in this case). I did not manage to test it.
=> fix: [#262] Restore ConfirmationBehavior with updated wicket-bootstrap

CHANGELOG.adoc, common/common-wicket/src/main/kotlin/ch/difty/scipamato/common/web/AbstractPanel.utf8.properties, common/common-wicket/src/main/kotlin/ch/difty/scipamato/common/web/AbstractPanel_de.utf8.properties, core/core-entity/src/main/java/ch/difty/scipamato/core/entity/search/PaperFilter.java, core/core-entity/src/test/kotlin/ch/difty/scipamato/core/entity/search/PaperFilterTest.kt, core/core-persistence-jooq/src/integration-test/kotlin/ch/difty/scipamato/core/persistence/paper/searchorder/StringSearchTermEvaluatorTest.kt, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/paper/PaperFilterConditionMapper.kt, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/paper/searchorder/StringSearchTermEvaluator.java, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/paper/PaperFilterConditionMapperTest.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel.utf8.properties, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/list/PaperListPage.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/list/PaperListPage.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/list/PaperListPage.utf8.properties, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/list/PaperListPage_de.utf8.properties, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/common/PaperPanelTest.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/jasper/summaryshort/PaperSummaryShortDataSourceTest.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/list/PaperListPageTest.kt
Resolves #306
- Extends the search in search field `population` to also search in `place/country`, `population`, `duration`.
- Introduces a new filter field `population` that respects the same fields (removing them from the generic search field).
=> feat(core): [#306] Population Filter & Search + some renames

CHANGELOG.adoc, buildSrc/src/main/kotlin/Lib.kt, common/common-persistence-jooq-test/src/main/kotlin/ch/difty/scipamato/common/persistence/FilterConditionMapperTest.kt, common/common-persistence-jooq/src/main/kotlin/ch/difty/scipamato/common/persistence/JooqSortMapper.kt, common/common-persistence-jooq/src/main/kotlin/ch/difty/scipamato/common/persistence/SortMapper.kt, common/common-persistence-jooq/src/test/kotlin/ch/difty/scipamato/common/persistence/SortMapperTest.kt, common/common-wicket/src/test/resources/application.yml, core/core-persistence-jooq/src/integration-test/kotlin/ch/difty/scipamato/core/persistence/paper/searchorder/StringSearchTermEvaluatorIntegrationTest.kt, core/core-persistence-jooq/src/integration-test/kotlin/ch/difty/scipamato/core/persistence/paper/searchorder/StringSearchTermEvaluatorTest.kt, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/JooqEntityRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/JooqReadOnlyRepo.java, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/JooqEntityRepoTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/JooqReadOnlyRepoTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/paper/slim/JooqPaperSlimBySearchOrderRepoTest.kt, core/core-persistence-jooq/src/test/kotlin/ch/difty/scipamato/core/persistence/search/SearchOrderFilterConditionMapperTest.kt, core/core-web/src/intTestDisabled/resources/application.yml, core/core-web/src/main/resources/application.properties, core/core-web/src/test/resources/application.properties, public/public-web/src/integration-test/resources/application.properties, public/public-web/src/main/resources/application.properties, public/public-web/src/test/resources/application.yml
Bumps:
* spring-boot from 2.5.7 to 2.6.0
* spring cloud from 2020.0.3 to 2021.0.0
* spring-cloud-starter from 3.0.3 to 3.1.0-RC1
* jOOQ from 3.14.15 to 3.15.4
Aligns the code with some changes in jOOQ between 3.14 and 3.15. Having to change this is a smell of mostly some of the tests in scipamato. They are too tightly coupled to the implementation of the third-party library and testing that logic should actually be moved to integration tests.
=> chore(deps): Bump spring-boot and related depenedencies

CHANGELOG.adoc, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/launcher/RefDataSyncJobLauncher.kt, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/launcher/SyncJobLauncher.kt, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/launcher/SyncJobResult.kt, core/core-sync/src/test/kotlin/ch/difty/scipamato/core/sync/launcher/RefDataSyncJobLauncherTest.kt, core/core-sync/src/test/kotlin/ch/difty/scipamato/core/sync/launcher/SyncJobResultTest.kt, core/core-web/src/main/java/ch/difty/scipamato/core/ScipamatoCoreApplication.kt, core/core-web/src/main/java/ch/difty/scipamato/core/ScipamatoSession.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/sync/BatchJobLaunchedEvent.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/sync/RefDataSyncPage.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/sync/RefDataSyncPage.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/sync/RefDataSyncPage.utf8.properties, core/core-web/src/main/java/ch/difty/scipamato/core/web/sync/RefDataSyncPage_de.utf8.properties, core/core-web/src/main/java/ch/difty/scipamato/core/web/sync/SyncBatchTask.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/sync/SyncResultDataProvider.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/sync/SyncResultListPanel.html, core/core-web/src/main/java/ch/difty/scipamato/core/web/sync/SyncResultListPanel.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/sync/SyncResultListPanel.utf8.properties, core/core-web/src/main/java/ch/difty/scipamato/core/web/sync/SyncResultListPanel_de.utf8.properties, core/core-web/src/main/webapp/style.css, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/sync/RefDataSyncPageTest.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/sync/SyncBatchTaskTest.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/sync/SyncResultDataProviderTest.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/sync/SyncResultListPanelTest.kt
resolves #344
Instead of handling the entire long-running spring-batch process in the AjaxRequest, the current implementation launches an async task for the spring batch job and let's the job put status messages into the session.The table displaying the step results queries the session for the incoming messages.
This hopefully solves the problem at the production instance of SciPaMaTo where the batch job starts running for too long. Something seems to kill the running request before the sync job results can be displayed to the user. So while the job still ran - and actually finished successfully - the results were not displayed and the user didn't know about the state of the job.
Inspired by [antilla-bits/bgprocess](https://github.com/reiern70/antilia-bits/tree/master/bgprocess) - thanks …
=> fix(sync): [#344] Async call to spring batch data synchronization core -> public

CHANGELOG.adoc, common/common-utils/src/main/kotlin/ch/difty/scipamato/common/paper/AbstractShortFieldConcatenator.kt, common/common-utils/src/test/kotlin/ch/difty/scipamato/common/paper/AbstractShortFieldConcatenatorWithNewLineTest.kt, common/common-utils/src/test/kotlin/ch/difty/scipamato/common/paper/AbstractShortFieldConcatenatorWithoutNewLineTest.kt, core/core-sync/src/main/kotlin/ch/difty/scipamato/core/sync/jobs/paper/SyncShortFieldConcatenator.kt, core/core-sync/src/test/kotlin/ch/difty/scipamato/core/sync/jobs/paper/SyncShortFieldWithEmptyMainFieldConcatenatorTest.kt
When sychronizing from core to public, the short fields are concatenated and fed into the regular fields (mehtods, population, results). There is a caption/label prepended to each field content. As this concatenation happens on synchronization time and not at view time, those labels do not respond to the browser locale set by the viewer.
The initial choice was to use english labels. The team now requested to switch the labels to german.
=> feat(sync): [#463] Swap labels for concatenated fields from EN to DE

build.gradle.kts, gradle-plugins/run/build.gradle.kts, gradle-plugins/verification/build.gradle.kts
Initial idea to be able to run scipamato on jvm 17.
This PR will not achieve that due to an incompatibility of Jooq in the version we use here.
Will be part of bumping SpringBoot, Jooq etc.
=> chore: fix jvmToolChain configuration

.github/workflows/check.yml, common/common-persistence-jooq/src/test/kotlin/ch/difty/scipamato/common/persistence/SortMapperTest.kt, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/JooqEntityRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/JooqReadOnlyRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/code/JooqCodeRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/codeclass/JooqCodeClassRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/keyword/JooqKeywordRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/newsletter/JooqNewsletterRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/paper/JooqPaperRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/paper/searchorder/JooqBySearchOrderRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/paper/slim/JooqPaperSlimRepo.java, core/core-persistence-jooq/src/main/java/ch/difty/scipamato/core/persistence/search/JooqSearchOrderRepo.java
In order to let SciPaMaTo run on a JVM 17 (still compiled to java 11), explicit imports for org.jooq.Record seem to be necessary.
Also applies formats to repos.
=> chore: let scipamato run on jvm 17

CHANGELOG.adoc, core/core-entity/src/main/java/ch/difty/scipamato/core/entity/Paper.java, core/core-entity/src/test/kotlin/ch/difty/scipamato/core/entity/PaperTest.kt, core/core-logic/src/main/kotlin/ch/difty/scipamato/core/logic/parsing/AuthorParserStrategies.kt, core/core-logic/src/test/kotlin/ch/difty/scipamato/core/logic/parsing/AuthorParsingTest.kt, core/core-pubmed-api/src/main/java/ch/difty/scipamato/core/pubmed/GreekLetterTranslator.kt, core/core-pubmed-api/src/main/java/ch/difty/scipamato/core/pubmed/PubmedArticleResult.kt, core/core-pubmed-api/src/main/java/ch/difty/scipamato/core/pubmed/PubmedXmlService.java, core/core-pubmed-api/src/main/java/ch/difty/scipamato/core/pubmed/ScipamatoPubmedArticle.java, core/core-pubmed-api/src/test/kotlin/ch/difty/scipamato/core/pubmed/GreekLetterTranslatorTest.kt, justfile, public/public-persistence-jooq/build.gradle.kts
fixes #528
Introduces a translator that replaces visually similar or identical characters from the set of greek capital letters) with their counterparts from the regular latin characters.
=> fix: [#528] Handle capital greek letters in PubMed authors to pass author field validation

build.gradle.kts, core/core-persistence-jooq/build.gradle.kts, gradle.properties, public/public-persistence-jooq/build.gradle.kts
- have gradle fail the build for gradle warnings
- resolve current warnings
- resolve some detekt warnings
- set property `sonar.skipCompile` to `true`  (see [here](https://sonarsource.atlassian.net/browse/SONARGRADL-130))
=> chore: fail on gradle warnings

.github/workflows/check.yml, .github/workflows/codeql.yml, core/core-persistence-jooq/build.gradle.kts, core/core-persistence-jooq/src/integration-test/resources/application.properties, public/public-persistence-jooq/build.gradle.kts, public/public-persistence-jooq/src/integration-test/resources/application.properties, public/public-persistence-jooq/src/main/resources/db/migration/V181030081000__new_study_topic_fk_fix.sql, public/public-web/src/integration-test/kotlin/ch/difty/scipamato/publ/config/HikariDatasourceProductionSettingsIntegrationTest.kt, public/public-web/src/integration-test/resources/application.properties
After upgrade of production instance of Scipamato from 10.6 to 15.4, we can bump the build implementations and the documentation too.
Note, for some reason, public flyway script `V181030081000__new_study_topic_fk_fix` tries to delete a constraint that does not exist (anymore). I added the `if exists` clause and also renamed the new index to not use too many characters (a warning so far).
However, if this fix is applied to a database that already ran the original patch, flyway will fail.
One will manually have to fix the checksum in the public database. I.e. as user `postgres` (adjust the database name from "scipamato_public" to whatever the name of the public database actually is):
```
psql
\c scipamato_public
update flyway_schema_history set checksum = 1627436357 where version = …
```
=> chore!: Bump postgres from 10.6 to 15.4

CHANGELOG.adoc, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/common/PaperPanel$TabPanel6.html
=> fix: [#701] Fix deleting attachments with long names

CHANGELOG.adoc, public/public-web/src/main/kotlin/ch/difty/scipamato/publ/web/paper/browse/PublicPaperDetailPage.kt
=> fix: [#708] Keep back-button hidden in public detail page after opening from search list

CHANGELOG.adoc, common/common-wicket/src/main/kotlin/ch/difty/scipamato/common/web/pages/AbstractMenuBuilder.kt
Resolves #727.
The target was set to "_blank" already, but for some reason the link would not open in a new browser tab.
Using PopupSettings results in opening the links in new browser windows. Good enough.
=> fix: [#727] Open external link in new browser page

CHANGELOG.adoc, core/core-web/src/main/java/ch/difty/scipamato/core/logic/exporting/RisAdapter.kt, core/core-web/src/test/kotlin/ch/difty/scipamato/core/logic/export/DefaultRisAdapterTest.kt
Fixes #848
Allows exporting papers with large pages indicateion to RIS, e.g. https://pubmed.ncbi.nlm.nih.gov/32733175/ with location "Dose Response. 2020; 18 (3): 1559325820942699."
The Adapter now tries to parse the page (any of start page and end page) using longs instead of ints. If it can't be parsed to the respecive numeric values, we fall back to `null`.
=> fix: [#848] Fix exportin papers with very long page indicateion to RIS format

CHANGELOG.adoc, core/core-entity/src/main/java/ch/difty/scipamato/core/entity/search/SearchOrder.java, core/core-entity/src/test/kotlin/ch/difty/scipamato/core/entity/search/SearchOrderTest.kt, core/core-web/src/main/java/ch/difty/scipamato/core/web/paper/entry/EditablePaperPanel.java, core/core-web/src/test/kotlin/ch/difty/scipamato/core/web/paper/entry/EditablePaperPanelInEditModeTest.kt
Amend the search order display name to include an exclamation mark if the search order has defined paper exclusions.
=> feat: [#911] Add exclamation mark to name of search orders with exclusions
